name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install busybox build-essential cmake asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python2.7 python3 python3-pip python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf intltool mkisofs rsync
          sudo timedatectl set-timezone "Asia/Shanghai"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          if [ "${{ env.DELETE_USELESS_FILES }}" == true ]
          then
              docker rmi $(docker images -q)
              sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
              sudo -E apt-get -y autoremove --purge
              sudo -E apt-get clean
              sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /usr/lib/jvm /opt/ghc /swapfile
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up OpenWrt environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc wget

      - name: Clone OpenWrt repository
        run: git clone https://github.com/openwrt/openwrt.git

      - name: Add additional feeds
        run: |
          echo 'src-git emortal https://github.com/scoout/immortalwrt.git' >> openwrt/feeds.conf.default
          echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall.git' >> openwrt/feeds.conf.default
          echo 'src-git passpackage https://github.com/xiaorouji/openwrt-passwall-packages.git' >> openwrt/feeds.conf.default
          echo 'src-git modemfeed https://github.com/koshev-msk/modemfeed.git' >> openwrt/feeds.conf.default
          echo 'src-git OpenClash https://github.com/vernesong/OpenClash.git' >> openwrt/feeds.conf.default
          echo 'src-git Rooter https://github.com/scoout/ROOterSource2305.git' >> openwrt/feeds.conf.default

      - name: Change kernel version
        run: |
          sed -i 's/KERNEL_PATCHVER:=5.15/KERNEL_PATCHVER:=6.1/g' openwrt/target/linux/x86/Makefile

      - name: Update feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a

      - name: Install feeds
        run: |
          ./scripts/feeds install -a

      - name: Configuration Customization - Build_x86_64
        env:
          CONFIG_FILE: 'x86_64.config'
        run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x ./customize.sh && ./customize.sh
          cd openwrt && make defconfig

      - name: Download package
        working-directory: ./openwrt
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Build firmware
        working-directory: ./openwrt
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=sc

      - name: Accelerate with cachewrtbuild
        if: env.CACHE_ACCELERATE == 'true'
        uses: klever1988/cachewrtbuild@main
        with:
          ccache: false
          toolchain: true
          skip: true
          clean: true
          prefix: ${{ github.workspace }}/openwrt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt
          path: openwrt/bin
