#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_x86

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialize Environment
      run: |
        set +e
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone Source Code
      run: |
        git clone --depth 1 https://github.com/openwrt/openwrt -b master openwrt

    - name: Update & Install Feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Import External Feeds - immortal
      working-directory: ./openwrt
      run: |
        git clone https://github.com/immortalwrt/immortalwrt.git immortalwrt
        cp -rf immortalwrt/package/emortal/autocore package/new
        cp -rf immortalwrt/package/utils/mhz package/utils
        git clone https://github.com/immortalwrt/immortalwrt-luci.git immortalwrt-luci
        cp -rf immortalwrt-luci/modules/luci-base feeds/luci/modules
        cp -rf immortalwrt-luci/modules/luci-mod-status feeds/luci/modules

    - name: Import External Feeds - passwall
      working-directory: ./openwrt
      run: |
        git clone https://github.com/xiaorouji/openwrt-passwall.git package/lienol
        git clone https://github.com/xiaorouji/openwrt-passwall-packages.git package/passwall 

    - name: Import External Feeds - xmm
      working-directory: ./openwrt
      run: |
        git clone https://github.com/koshev-msk/modemfeed.git package/modemfeed
       
    - name: Configuration Customization - Build_x86
      env:
        CONFIG_FILE: 'x86.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: Download Packages
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build Firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=sc

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt
        path: openwrt/bin
        
